-- CURSOR SIMPLE A LA TABLA CLIENTE
DECLARE
    CURSOR C_CLIENTES IS
    SELECT * FROM CLIENTE;
BEGIN
    FOR CADA_CLIENTE IN C_CLIENTES LOOP
        DBMS_OUTPUT.PUT_LINE('Nombre: '||CADA_CLIENTE.Nombre);
        DBMS_OUTPUT.PUT_LINE('Rut: '||CADA_CLIENTE.Rut);
    END LOOP;
END;
/

-- CURSOR CON WHERE
DECLARE
    CURSOR C_CLIENTES IS 
        SELECT *
        FROM CLIENTE
        WHERE NOMBRE LIKE '%a%';
v_contador number:= 1;
BEGIN
    FOR CADA_CLIENTE IN C_CLIENTES LOOP
        DBMS_OUTPUT.PUT_LINE('Nombre: '||CADA_CLIENTE.Nombre);
        DBMS_OUTPUT.PUT_LINE('Rut: '||CADA_CLIENTE.Rut);
        DBMS_OUTPUT.PUT_LINE('Contador: '||v_contador);
        v_contador:= v_contador+1;
    END LOOP;
END;
/

-- CURSOR CON JOINS
-- GENERAR UN REPORTE CON TODAS LAS TRANSACCIONES APROBADAS
DECLARE
    CURSOR C_CLIENTE IS 
        SELECT NOMBRE, C.RUT, MONTO_BRUTO, DESCUENTO, MONTO_FINAL, TP.ESTADO
        FROM TRANSACCION_PAGO TP
        INNER JOIN RESERVA_TEMPORAL R ON TP.RESERVA_ID = R.RESERVA_ID
        INNER JOIN CLIENTE C ON R.CLIENTE_ID = C.CLIENTE_ID
        WHERE TP.ESTADO = 'APROBADO';
BEGIN
    FOR CADA_CLIENTE IN C_CLIENTE LOOP
        DBMS_OUTPUT.PUT_LINE('Nombre: '||CADA_CLIENTE.Nombre);
        DBMS_OUTPUT.PUT_LINE('Rut: '||CADA_CLIENTE.RUT);
        DBMS_OUTPUT.PUT_LINE('Monto Final: '||CADA_CLIENTE.MONTO_FINAL);
        DBMS_OUTPUT.PUT_LINE('Estado: '||CADA_CLIENTE.Estado);
        DBMS_OUTPUT.PUT_LINE('------------------------------');
    END LOOP;
END;
/

-- INSERTS
INSERT INTO CLIENTE(RUT, NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHA_REGISTRO)
VALUES('11.111.111-1', 'Fernandito', 'Vargas', 'fvargas@gmail.com', '+56912386953', SYSTIMESTAMP);
INSERT INTO CLIENTE(RUT, NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHA_REGISTRO)
VALUES('22.222.222-2', 'Luciana', 'Vargas', 'lvargas@gmail.com', '+56958157346', SYSTIMESTAMP);
INSERT INTO CLIENTE(RUT, NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHA_REGISTRO)
VALUES('33.333.333-3', 'Ricardito', 'Vargas', 'rvargas@gmail.com', '+56948635826', SYSTIMESTAMP);
COMMIT;

SELECT * FROM CLIENTE;

-- CURSOR CON PARAMETROS
DECLARE
    CURSOR C_CLIENTE(P_APELLIDO VARCHAR2) IS 
        SELECT CLIENTE_ID, NOMBRE, APELLIDO, EMAIL
        FROM CLIENTE
        WHERE APELLIDO = P_APELLIDO;
BEGIN
    FOR UN_CLIENTE IN C_CLIENTE('Vargas') LOOP
        DBMS_OUTPUT.PUT_LINE(UN_CLIENTE.NOMBRE);
    END LOOP;
END;
/