SELECT C.NOMBRE, TP.MONTO_BRUTO, TP.DESCUENTO, TP.MONTO_FINAL, TP.ESTADO
FROM TRANSACCION_PAGO TP
INNER JOIN RESERVA_TEMPORAL R ON TP.RESERVA_ID = R.RESERVA_ID
INNER JOIN CLIENTE C ON R.CLIENTE_ID = C.CLIENTE_ID
WHERE C.CLIENTE_ID = 1;

DECLARE
TYPE TRANSACCION IS RECORD(
    NOMBRE_CLIENTE CLIENTE.NOMBRE%TYPE,
    MONTO_BRUTO TRANSACCION_PAGO.MONTO_BRUTO%TYPE,
    DESCUENTO TRANSACCION_PAGO.DESCUENTO%TYPE,
    MONTO_FINAL TRANSACCION_PAGO.MONTO_FINAL%TYPE,
    ESTADO TRANSACCION_PAGO.ESTADO%TYPE
);

V_BOLETA TRANSACCION;
BEGIN
    SELECT NOMBRE, MONTO_BRUTO, DESCUENTO, MONTO_FINAL, TP.ESTADO
    INTO V_BOLETA.NOMBRE_CLIENTE, V_BOLETA.MONTO_BRUTO, V_BOLETA.DESCUENTO, V_BOLETA.MONTO_FINAL, V_BOLETA.ESTADO
    FROM TRANSACCION_PAGO TP
    INNER JOIN RESERVA_TEMPORAL R ON TP.RESERVA_ID = R.RESERVA_ID
    INNER JOIN CLIENTE C ON R.CLIENTE_ID = C.CLIENTE_ID
    WHERE C.CLIENTE_ID = 1;

    DBMS_OUTPUT.PUT_LINE(V_BOLETA.NOMBRE_CLIENTE||' '||V_BOLETA.MONTO_BRUTO||' '||V_BOLETA.DESCUENTO||' '||V_BOLETA.MONTO_FINAL||' '||V_BOLETA.ESTADO);
END;