CREATE OR REPLACE FUNCTION OBTENER_RECINTO(
    P_RECINTO_ID IN NUMBER
) RETURN NUMBER
AS
TYPE R_RECINTO_INFO IS RECORD(
    NOMBRE_RECINTO RECINTO.NOMBRE%TYPE,
    DIRECCION_RECINTO RECINTO.DIRECCION%TYPE,
    CIUDAD_RECINTO RECINTO.CIUDAD%TYPE,
    CAPACIDAD_TOTAL RECINTO.CAPACIDAD_TOTAL%TYPE
);
INFO_RECINTO R_RECINTO_INFO;
P_RECINTO_ID RECINTO_ID;
BEGIN
    SELECT NOMBRE, DIRECCION, CIUDAD, CAPACIDAD_TOTAL
    INTO INFO_RECINTO.NOMBRE_RECINTO, INFO_RECINTO.DIRECCION_RECINTO, INFO_RECINTO.CIUDAD_RECINTO, INFO_RECINTO.CAPACIDAD_TOTAL
    FROM RECINTO
    WHERE RECINTO_ID = RECINTO_ID;

    DBMS_OUTPUT.PUT_LINE('Nombre recinto: '||INFO_RECINTO.NOMBRE_RECINTO);
    DBMS_OUTPUT.PUT_LINE('Direccion: '||INFO_RECINTO.DIRECCION_RECINTO);
    DBMS_OUTPUT.PUT_LINE('Ciudad: '||INFO_RECINTO.CIUDAD_RECINTO);
    DBMS_OUTPUT.PUT_LINE('Capacidad total: '||INFO_RECINTO.CAPACIDAD_TOTAL);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Recinto'||INFO_RECINTO.NOMBRE_RECINTO||'no encontrado');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('La consulta retornó mas de un recinto');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Codigo: '||SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensaje: '||SQLERRM);
END;
/