SELECT * FROM CLIENTE;
INSERT INTO CLIENTE(RUT, NOMBRE, APELLIDO, EMAIL) VALUES('18.125.154-4', '  m Ar Tin ', '   p APic ', 'M Pa piCcCc @gmail. c Om ');
COMMIT;

CREATE OR REPLACE TRIGGER TGR_VALIDACION_DATOS_CLIENTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    :NEW.NOMBRE:= INITCAP(TRIM(REPLACE(:NEW.NOMBRE, ' ', '')));
    :NEW.APELLIDO:= INITCAP(TRIM(REPLACE(:NEW.APELLIDO, ' ', '')));
    :NEW.EMAIL:= LOWER(TRIM(REPLACE(:NEW.EMAIL, ' ', '')));
END TGR_VALIDACION_DATOS_CLIENTE;
/