-- Forma de rellenar un VARRAY de forma NO PROCEDURAL
DECLARE
TYPE LISTA_ASIENTOS IS VARRAY(6) OF VARCHAR2(3);
V_ASIENTO LISTA_ASIENTOS := LISTA_ASIENTOS('A01', 'A02', 'A03', 'A04', 'A05', 'A06');
BEGIN
    DBMS_OUTPUT.PUT_LINE('Se ha asignado el asiento N°'|| V_ASIENTO(2));
END;
/

DECLARE
TYPE LISTA_RUT IS VARRAY(3) OF VARCHAR2(12);
V_RUT LISTA_RUT := LISTA_RUT('18.843.627-1', '21.938.372-0', '20.654.820-6');
BEGIN
    DBMS_OUTPUT.PUT_LINE('RUT: '||V_RUT(2));
END;
/

-- Forma PROCEDURAL
DECLARE
TYPE LISTA_RUT IS VARRAY(3) OF VARCHAR2(12);
V_RUT LISTA_RUT := LISTA_RUT();
BEGIN
    V_RUT.EXTEND;
    V_RUT(1) := '11.111.111-1';
    V_RUT.EXTEND;
    V_RUT(2) := '22.222.222-2';
    V_RUT.EXTEND;
    V_RUT(3) := '33.333.333-3';

    DBMS_OUTPUT.PUT_LINE('RUT: '||V_RUT(1));
    DBMS_OUTPUT.PUT_LINE('RUT: '||V_RUT(2));
    DBMS_OUTPUT.PUT_LINE('RUT: '||V_RUT(3));
END;
/