DECLARE
CURSOR CUR_RECINTOS IS
SELECT R.NOMBRE, COUNT(T.TICKET_ID) AS CANTIDAD_TICKETS
FROM RECINTO R
INNER JOIN EVENTO E ON R.RECINTO_ID = E.RECINTO_ID
INNER JOIN LOCALIDAD_EVENTO LE ON E.EVENTO_ID = LE.EVENTO_ID
INNER JOIN RESERVA_TEMPORAL RT ON LE.LOCALIDAD_EVENTO_ID = RT.LOCALIDAD_EVENTO_ID
INNER JOIN TICKET T ON RT.RESERVA_ID = T.RESERVA_ID
GROUP BY R.NOMBRE
ORDER BY COUNT(T.TICKET_ID) DESC;

V_RECINTOS CUR_RECINTOS%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE(' RECINTOS CON MAYOR CANTIDAD DE TICKETS VENDIDOS');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
    OPEN CUR_RECINTOS;
    LOOP
        FETCH CUR_RECINTOS INTO V_RECINTOS;
        EXIT WHEN CUR_RECINTOS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('NOMBRE RECINTO: '||UPPER(V_RECINTOS.NOMBRE)||' | TICKETS VENDIDOS: '|| V_RECINTOS.CANTIDAD_TICKETS);
    END LOOP;
END;

SELECT * FROM RECINTO;
SELECT * FROM TICKET;
SELECT * FROM EVENTO;
SELECT * FROM RESERVA_TEMPORAL;
SELECT * FROM LOCALIDAD_EVENTO;