CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE(
    P_RUT IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_APELLIDO IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_TELEFONO IN VARCHAR2
)
AS

BEGIN
    INSERT INTO CLIENTE(RUT, NOMBRE, APELLIDO, EMAIL, TELEFONO) VALUES(P_RUT, P_NOMBRE, P_APELLIDO, P_EMAIL, P_TELEFONO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Usuario registrado');
END INSERTAR_CLIENTE;
/

-- CREAR UN PROCEDIMIENTO QUE RETORNE LOS DATOS DE UN CLIENTE SEGUN SU ID
CREATE OR REPLACE PROCEDURE OBTENER_CLIENTE(
    P_CLIENTE_ID IN NUMBER,
    P_RUT OUT VARCHAR2,
    P_NOMBRE OUT VARCHAR2,
    P_APELLIDO OUT VARCHAR2,
    P_EMAIL OUT VARCHAR2,
    P_TELEFONO OUT VARCHAR2
)
IS

BEGIN
    SELECT RUT, NOMBRE, APELLIDO, EMAIL, TELEFONO
    INTO P_RUT, P_NOMBRE, P_APELLIDO, P_EMAIL, P_TELEFONO
    FROM CLIENTE
    WHERE CLIENTE_ID = P_CLIENTE_ID;
END OBTENER_CLIENTE;
/

DROP PROCEDURE OBTENER_CLIENTE;