BEGIN
    INSERTAR_CLIENTE('18.291.255-7', 'Jose', 'Sanchez', 'jperere@gmail.com', null);
END;
/

DECLARE
V_RUT CLIENTE.RUT%TYPE;
V_NOMBRE CLIENTE.NOMBRE%TYPE;
V_APELLIDO CLIENTE.APELLIDO%TYPE;
V_EMAIL CLIENTE.EMAIL%TYPE;
V_TELEFONO CLIENTE.TELEFONO%TYPE;
BEGIN
    OBTENER_CLIENTE(1, V_RUT, V_NOMBRE, V_APELLIDO, V_EMAIL, V_TELEFONO);
    DBMS_OUTPUT.PUT_LINE('RUT: '||V_RUT);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
    DBMS_OUTPUT.PUT_LINE('APELLIDO: '||V_APELLIDO);
    DBMS_OUTPUT.PUT_LINE('EMAIL: '||V_EMAIL);
    DBMS_OUTPUT.PUT_LINE('TELEFONO: '||V_TELEFONO);
END;
/