-- FUNCION QUE SUMA 10
CREATE OR REPLACE FUNCTION SUMAR_DIEZ(
    NUMERO IN NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN NUMERO + 10;
END;
/

SELECT SUMAR_DIEZ(5) AS RESULTADO
FROM DUAL;

-- FUNCION QUE RETORNA LA RAIZ CUADRADA
CREATE OR REPLACE FUNCTION raiz_cuadrada(
    p_numero IN NUMBER
)
RETURN NUMBER
IS
v_numero NUMBER;
BEGIN
    v_numero := p_numero * p_numero;
    RETURN v_numero;
END;
/

SELECT raiz_cuadrada(15) AS resultado
FROM DUAL;

-- FUNCION PARA APLICAR EL DESCUENTO A UN VALOR
CREATE OR REPLACE FUNCTION APLICAR_DESCUENTO(
    P_ID_BANCO IN NUMBER,
    P_COSTO IN NUMBER
)
RETURN NUMBER
IS
V_PRECIO_FINAL NUMBER;
V_DESCUENTO NUMBER;
BEGIN
    SELECT DESCUENTO_PORCENTAJE
    INTO V_DESCUENTO
    FROM CONVENIO_BANCO
    WHERE P_ID_BANCO = CONVENIO_BANCO_ID
    AND ACTIVO = 'S';
    
    V_PRECIO_FINAL := P_COSTO - (P_COSTO * V_DESCUENTO / 100);
    RETURN V_PRECIO_FINAL;
END;
/

SELECT APLICAR_DESCUENTO(1, 10000) AS RESULTADO FROM DUAL;